# -*- coding: utf-8  -*-
"""
triquad.py - Gauss quadrature for triangles

Copyright (C) 2014 Greg von Winckel

Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated 
documentation files (the "Software"), to deal in the 
Software without restriction, including without limitation 
the rights to use, copy, modify, merge, publish, 
distribute, sublicense, and/or sell copies of the Software,
and to permit persons to whom the Software is furnished to 
do so, subject to the following conditions:

The above copyright notice and this permission notice shall
be included in all copies or substantial portions of the 
Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY 
KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE 
WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR 
PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS 
OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR 
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

import numpy as np
import orthopoly as op

def triquad(n):
    """
        Compute the quadrature nodes and weights for integrating a
        function f(x,y) over a triangle with vertices {(-1,-1),(-1,1),(1,-1)}

        The quadrature rule is generated by using a Duffy transformation to map
        the square to the triangle 
    """
    alphax,betax = op.rec_jacobi(n,0,1)
    x,wx = op.gauss(alphax,betax)
    x = (1+x)/2
    wx = wx/2

    alphat,betat = op.rec_jacobi(n,0,0)
    t,wt = op.gauss(alphat,betat)
    t = (1+t)/2
    wt = wt

    tt, xx = np.meshgrid(t,x)
    yy = xx*tt

    xx = 1-2*xx
    yy = 2*yy-1

    ww = np.outer(wx,wt)
    
    xx = xx.flatten()
    yy = yy.flatten()
    ww = ww.flatten()

    return xx,yy,ww

